"""add groups 4 and 5

Revision ID: 0625cfd877dd
Revises: f6211a55986e
Create Date: 2026-04-08 17:53:03.906923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0625cfd877dd'
down_revision: Union[str, Sequence[str], None] = 'f6211a55986e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_downloads', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group4_passed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('group5_passed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notified_4g_exp_7d', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notified_4g_exp_1d', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notified_5g_exp_7d', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notified_5g_exp_1d', sa.Boolean(), nullable=True))
        batch_op.drop_column('company')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('notified_5g_exp_1d')
        batch_op.drop_column('notified_5g_exp_7d')
        batch_op.drop_column('notified_4g_exp_1d')
        batch_op.drop_column('notified_4g_exp_7d')
        batch_op.drop_column('group5_passed_at')
        batch_op.drop_column('group4_passed_at')

    with op.batch_alter_table('document_downloads', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
