"""add_is_supervisor_column

Revision ID: 3ff4ca035a23
Revises: 082572b9279e
Create Date: 2026-06-02 11:48:09.406678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff4ca035a23'
down_revision: Union[str, Sequence[str], None] = '082572b9279e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_supervisor', sa.Boolean(), nullable=True, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_supervisor')

    # ### end Alembic commands ###
