"""Add notified_3g_exp_7d and notified_3g_exp_1d to User

Revision ID: f6211a55986e
Revises:
Create Date: 2026-04-08 13:40:33.421623

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6211a55986e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("notified_3g_exp_7d", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("notified_3g_exp_1d", sa.Boolean(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("notified_3g_exp_1d")
        batch_op.drop_column("notified_3g_exp_7d")
    # ### end Alembic commands ###
